### ISSUE TITLE
Decide on flat files or database.

### ISSUE THREAD

**Issue by LeamHall** [makhidkarun/ftl_tools#9]
DB has more application set up, flat files have easier user modification.
DB is a standard, and it might filter out user mistakes.
- Sort of a "barrier to entry" for modification.

**Comment by COliver988** [comment]
other alternatives do include JSON or XML, Ruby can serialize to/from those easily (or so I believe). I know our work uses SQLite by default on the dev machines and that is easy enough to deal with (well, we use Rails so maybe not as easy in Ruby as-is. It was simple enough in my .Net programs to implement).

I'd probably go with SQLite assuming there is a gem and the models/data layers are set up to make that, once set up, easy to deal with (such as models inheriting from some base class that has the DB stuff built in so it is pretty much automatic).

**Comment by LeamHall** [comment]
I tend not to use XML in polite company, but JSON is one of my usual choices. SQLite is another, and if you check out 

https://github.com/makhidkarun/ftl_tools/blob/master/lib/ftl_tools/name.rb#L45-L48

You can see just how easy it is. If someone wanted to do a larger DB back-end, changing the code wouldn't be that difficult. One thing that really needs work is the user documentation; how to add to or change DB data. Flat files tend to be easier in that regard. 

Most of the data pulls devolve to "pull one item from the options". The above link shows it in DB terms, or you can look at the file method in "lib/ftl_tools/data_mine.rb". Ruby arrays have a "sample" method that gives you X number of random results from the array.

**Comment by COliver988** [comment]
could do something similar to your ftl_tools library - it does seem simple enough.  And there are some nice tools to manage SQLite outside of your application.

If going that route, I'd actually abstract a bit more and make the actual query a method call, so that all the rescue/ensure stuff is just in 1 place. And in general, although at the likely scale here not an issue, you do not want to do a SELECT * - it is inefficient and not always determinate in the order you may get things back in. I may try to contribute as I do need to get Ruby set up at home so I can start contributing that way to work, and Traveller is just more fun (most of my college years was spent playing Traveller and programming little tools for Traveller: that hex thing just fit right in with a lot of things I was learning :) )

Re: XML: it has some advantages over JSON (see XSL for formatting, just like CSS for HTML; and can better handle more complicated things). But yes, JSON is currently the lingua franca for data exchange now.

**Comment by LeamHall** [comment]
Hmm...not sure why the "SELECT *" is still there, the tables only have one field and an index. The major work is just to get one random response. The name pulls are split because some things use or order first or last names. Something to think about.

Still pondering the flat file issue. There are several upcoming data sets that are usually in the dozen to just under a hundred range. Things like skin tone, hair color, skill sets, etc. What are your thoughts on making it super easy for a user to modify their copies of the data? While a database would be more efficient, it's one more skill to document for the end user. Of course, someone has to be mildly conversant with coding to use any of this, I think, and a little SQL is always useful.

**Comment by COliver988** [comment]
What I have done in the past, using a text file, is load the file into memory, get the number of lines, and generate a random number within that range to get a random record. So if going with flat files, would you go with files for each attribute, or a JSON file, and then load that JSON and for each category, get a random attribute?

```json
{
	"categories": [{
		"skin tone": ["red", "white", "blue"]
	}, {
		"hair color": ["pink", "purple", "orange"]
	}, {
		"sophonts": ["Terran", "Vilani", "Aslan", "Vargr", "Bwap"]
	}]
}
```

**Comment by LeamHall** [comment]
The current setup, in lib/ftl_tools/data_mine.rb#L12-L15, is to build an array of data, one item per line, and then use Ruby's "sample" to take random items. We can expand this since sample can take a number of items to be returned. This could work with straight data files and JSON stored arrays, too.

A user should be able to easily modify the sampled item names and probabilities. For example, if there's a list of Navy Enlisted skills, a user might want VaccSuit to show up more often and GunCbt to show up less. 

JSON is language agnostic, which I really like. The main down side is the ease of use for a beginner. Syntax issues will kill a JSON load quickly, and then it looks like our program failed.

**Comment by LeamHall** [comment]
Separating the character creation from the storage and game (free_trader) gems. Moving to flat files and a directory tree so others can use/modify to fit their needs.
